### ISSUE TITLE
release a new version 

### ISSUE THREAD

**Issue by patte** [ElevateDev/meteor-autoform-nouislider#14]
hi! would you mind releasing the newest version to atmosphere? thx!

**Comment by jimmiebtlr** [comment]
If your talking about nouislider version ~8.2, the upstream package isn't up to date.  I went ahead and put an issue there.

**Comment by patte** [comment]
thank you for this. but I actually was referring to your package. You merged a pull request of mine and it would be very cool if I can directly use your package instead of mine, but IMHO there is no version released with it yet, atmosphere says the last one is from august 2015?

**Comment by jimmiebtlr** [comment]
Looks like in August I had deployed as 0.1.0, then went backward on version number for some reason.  Bumped the version to 0.1.1 which should resolve this.  Sorry for the delay.
