### ISSUE TITLE
Meteorpad of example yields 'Unexpected object in htmljs in toText'

### ISSUE THREAD

**Issue by jiku** [ElevateDev/meteor-autoform-nouislider#3]
I'm trying to implement your example on [Meteorpad](http://meteorpad.com/pad/mJkQdgCKzHY6NLjHK/Autoform%20noUiSlider%20%28JS%29). The form renders fine when removing slider from the CollectionSchema, but adding it yields `'Unexpected object in htmljs in toText'`` in the console (opening the dynamic app URL in a new tab).

Would you mind taking a look and seeing if you can get it to work?

UPDATE: It works when changing to [fuatsengul:autoform-nouislider](http://meteorpad.com/pad/dAgw5oMGCSrT7Afr4/Autoform%20with%20fuatsengul:noUiSlider%20%28JS%29).

**Comment by jimmiebtlr** [comment]
When I switch you're meteorpad to autoform-nouislider it uses version 0.0.1, it should use 0.0.3.

The only difference between fuatsengul:autoform-nouislider, is it try's to avoid overwriting start if it's defined ( though the logic appears backward, so it only overwrites when the option is present ).

**Comment by jimmiebtlr** [comment]
Also, you're application is using an identical schema to my test application, I would say the version is just out of date.
