### ISSUE TITLE
slider not reactive?

### ISSUE THREAD

**Issue by stefanve** [ElevateDev/meteor-autoform-nouislider#5]
I have a schema with one select and one slider and autosave=true. When I move the slider, the value is updated, but only once. After that,nothing happens when I move the slider until I change something else (the select in this case). After that the slider is active again. 

At initial load (an update form), the slider sets itself at the correct value but if I change the value in the db (using Mongol) the slider does not react on it. If I on the other hand change the value for the select, in Mongol, it will immediately react on the new value. I do not see what I can have done wrong.

**Comment by jimmiebtlr** [comment]
I added the demo app I've been using, it appears to not be having trouble with autosave.  Take a look, if you don't find the issue, submit a minimal reproduction.

**Comment by jimmiebtlr** [comment]
What version of auto-form are you using with it?

**Comment by jimmiebtlr** [comment]
@stefanve Would you mind checking in the most recent version 0.1.0.

**Comment by stefanve** [comment]
Oh, sorry, forgot to track this. Yes, it seems to work fine now but a lot of code has changed around it (or rather around what I used instead) so I can not say for certain that there was a problem with the slider that is now fixed or a problem with my code that is now fixed... So it goes sometimes :)
