### ISSUE TITLE
Is there a way to use events on this slider ?

### ISSUE THREAD

**Issue by TimoRuetten** [ElevateDev/meteor-autoform-nouislider#6]
I am not sure if its possible yet to use events for this slider ? noUiSlider seems not to be available global in meteor App and so I am not able to use events (like on update) for the slider. 

Is there any way to do this with your package ?

**Comment by jimmiebtlr** [comment]
To get it in global scope you can add this package (used by noUiSlider already).

`rcy:nouislider`

Also, you should be able to do something along the lines of 

`$('.nouislider').val();`

(untested)

What hooks are you trying to use, and can you provide you're use case for them?

**Comment by TimoRuetten** [comment]
Ah - thanks! I just saw that the Schema name isnt available in the dom as the input but didnt took a look what other input field is there (.nouislider). Thanks for the hint :)
