### ISSUE TITLE
Value gets reset when form redrawn

### ISSUE THREAD

**Issue by oskarszoon** [ElevateDev/meteor-autoform-nouislider#7]
Hi there,

I'm having a minor issue when using the slider component with a single value. It seems if I change the slider, submit the form, leave the page and come back, the slider will always render using the initial value and not the new one the user submitted.

The problem lies in the storage of the template.data.atts.noUiSliderOptions, which stores the initial value as "start", after which all next renders will actually use that initial value instead of the defined template.data.value from the template data. I believe that template.data.value should always be leading when initializing options on re-renders of the component.

A simple refresh of the page fixes everything, but that's not the best solution :)

**Comment by jimmiebtlr** [comment]
This should be fixed in 0.0.6.  Could you verify and close if fixed.

**Comment by oskarszoon** [comment]
@jimmiebtlr Fixed, thanks!
