### ISSUE TITLE
Slider widget not working - only one slider which does not move

### ISSUE THREAD

**Issue by ouya99** [ElevateDev/meteor-autoform-nouislider#9]
Hi,

I have followed the guide from https://github.com/ElevateDev/meteor-autoform-nouislider
and set up the basic sliders, yet what I get on the AutoForm is only this.
![sliders](https://cloud.githubusercontent.com/assets/2676451/11021283/de31b838-863c-11e5-936b-86ef5ad87754.png)

I cannot move both sliders. There is no range either.

My setup is the following:

  singleSlider: {

```
type: Number,

max: 150,

min: 30,

autoform: {

  type: "noUiSlider",

  noUiSliderOptions: {

    step: 10

  },

  noUiSlider_pipsOptions: {

    mode: 'steps',

    density: 5

  }

}
```

  },

  slider: {

```
type: RangeSchema,

max: 200,

min: 10,

autoform: {

  type: "noUiSlider",

  noUiSliderOptions: {

    step: 10

  },

  noUiSlider_pipsOptions: {

    mode: 'steps',

    density: 5

  }

}
```

  }

  Settings.insert({

```
 pushNotifications: true,

 singleSlider: 30,

 slider: {"lower": 10,"upper":200}
```

   });

```
    {{#if Template.subscriptionsReady}}

    {{#autoForm collection="Settings" type=update doc=setting id="edit-form" autosave=true}}

        {{> afQuickField name='slider' start="[50,60]"}}

        {{> afQuickField name='singleSlider' range='{"min": 30,"max":50}'}}

    {{/autoForm}}
```

 {{/if}}

Thank you for any clue or link to a working sample. 

Cheers
java99

**Comment by jimmiebtlr** [comment]
Try specifying a width for .nouislider in your css.

**Comment by ouya99** [comment]
I see and I did set

.no-ui-slider {
    width: 100%;
}

with no effect, yet applying the whole css layout from
http://codepen.io/jacobhummel/pen/pjmKL/

did at least change the style of the slider.

Could you say or point to a file where I get a default layout (css) from?

**Comment by ouya99** [comment]
Got it

.at-nouislider{
    width: 50%;
}

Solved it. Thx
